name: Meson CI

on:
    push:
        branches: ["master"]
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip ninja
                  pip install meson

            - name: Setup GCC
              uses: egor-tensin/setup-gcc@v1
              with:
                  version: 13
                  platform: x64

            - name: setup and compile libressl
              run: |
                  wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.8.0.tar.gz
                  tar xzf libressl-3.8.0.tar.gz
                  cd libressl-3.8.0
                  ./configure
                  make
                  sudo make install

            - name: Configure
              run: meson setup build -Dbuildtype=release -Dtests=true

            - name: Build
              run: meson compile -C build

            - name: Test
              run: meson test -C build
